"""
 the connections to your datasource, such as database, url, or your local docs.

 db_conn.py: mysql, redis, mongodb, elastic search ...
 doc_conn.py: PPT, PDF, TEXT,...
 url_conn.py: google search, baidu, bing...
 xxx_conn.py: ...
"""
